# set.seed(1234)
# X <- rnorm(100)
# M1 <- 0.5*X + rnorm(100)
# M2 <-0.6*X + rnorm(100)
# Y <- 0.3*M1 + 0.4*M2 + rnorm(100)
# data <- data.frame(X = X, Y = Y, M1 = M1, M2 = M2)
# str(data)
# require(lavaan)
# require(semPlot)
#
# require(ggplot2)
# model=makeEquation(X="X",M=c("M1","M2"),Y="Y")
# cat(model)
# fit=sem(model,data=data)
# summary(fit)
# par(family="NanumGothic")
# semPaths(fit,rotation=2)
#
# mediationPlot(fit)
# mediationPlot(fit,mode=2)
